export const employees = [
    { name: 'Юрий', role: 'Чайка-приемщик', productivity: 60, mood: '', star: false, cup: false },
    { name: 'Михаил', role: 'Чайка-переместитель', productivity: 90, mood: '', star: false, cup: false },
    { name: 'Татьяна', role: 'Чайка-контролер', productivity: 80, mood: '', star: false, cup: false },
    { name: 'Николай', role: 'Чайка-отборщик', productivity: 90, mood: '', star: false, cup: false },
    { name: 'Сергей', role: 'Чайка-приемщик', productivity: 70, mood: '', star: false, cup: false },
    { name: 'Людмила', role: 'Чайка-приемщик', productivity: 45, mood: '', star: false, cup: false },
    { name: 'Анна', role: 'Чайка-отборщик', productivity: 90, mood: '', star: false, cup: false },
    { name: 'Катерина', role: 'Чайка-отборщик', productivity: 90, mood: '', star: false, cup: false },
    { name: 'Николай', role: 'Чайка-переместитель', productivity: 90, mood: '', star: false, cup: false },
    { name: 'Иван', role: 'Чайка-отборщик', productivity: 90, mood: '', star: false, cup: false },
    { name: 'Олег', role: 'Чайка-отборщик', productivity: 90, mood: '', star: false, cup: false },
    { name: 'Александр', role: 'Чайка-отборщик', productivity: 90, mood: '', star: false, cup: false },
    { name: 'Ольга', role: 'Чайка-приемщик', productivity: 80, mood: '', star: false, cup: false },
    { name: 'Денис', role: 'Чайка-отборщик', productivity: 90, mood: '', star: false, cup: false },
    { name: 'Галина', role: 'Чайка-контролер', productivity: 80, mood: '', star: false, cup: false },
    { name: 'Виктор', role: 'Чайка-отборщик', productivity: 90, mood: '', star: false, cup: false },
    { name: 'Евгений', role: 'Чайка-отборщик', productivity: 90, mood: '', star: false, cup: false },
    { name: 'Сергей', role: 'Чайка-переместитель', productivity: 90, mood: '', star: false, cup: false },
    { name: 'Александр', role: 'Чайка-переместитель', productivity: 90, mood: '', star: false, cup: false },
    { name: 'Ярослав', role: 'Чайка-переместитель', productivity: 90, mood: '', star: false, cup: false },
  ];